/**
 * CLI entrypoint — generate Google Ads campaigns from keyword-groups.ts.
 *
 *   npm run ads:sync                 # all routed landing pages
 *   npm run ads:sync web-development-company   # one slug
 *   npm run ads:sync -- --push       # Phase 2: push via Google Ads API (stub for now)
 *
 * Writes, per page:  docs/ads/<slug>.csv      (Editor import: 1 campaign, 1 ad group)
 *                     docs/ads/<slug>.md       (negatives + extensions + checklist)
 * And a combined:     docs/ads/all-campaigns.csv (1 campaign, every page as an ad group)
 *
 * Created PAUSED. A slug with no dedicated route is reported and skipped so a
 * broken Final URL never ships.
 */

import fs from "node:fs";
import path from "node:path";
import { keywordGroups } from "../../src/data/keyword-groups.ts";
import { buildRouteMap } from "./route-map.mts";
import { buildCampaign, type Campaign } from "./build-campaign.mts";
import { toEditorCsv } from "./to-editor-csv.mts";
import { apiCredentialsPresent, pushToGoogleAds } from "./to-ads-api.mts";
import {
  DOMAIN, CAMPAIGN_NAME, DAILY_BUDGET, BID_STRATEGY, NEGATIVES, CALLOUTS,
  STRUCTURED_SNIPPET, PHONE,
} from "./config.mts";

const OUT = path.resolve(process.cwd(), "docs/ads");
fs.mkdirSync(OUT, { recursive: true });

const args = process.argv.slice(2);
const push = args.includes("--push");
const slugFilter = args.find((a) => !a.startsWith("--"));

const routeMap = buildRouteMap();

function companionMd(c: Campaign): string {
  return `# Google Ads — ${c.adGroup}

**Landing page:** ${c.finalUrl}
**Campaign:** ${CAMPAIGN_NAME} · ₹${DAILY_BUDGET}/day · All India · ${BID_STRATEGY} (created PAUSED)
**Ad group:** ${c.adGroup} — ${c.keywords.length} keywords (phrase + exact), 1 RSA

> Auto-generated by \`npm run ads:sync\`. Edit copy in \`src/data/keyword-groups.ts\` and re-run — do not hand-edit this file.

## 1. Import
Google Ads Editor → Account → Import → From file → \`docs/ads/${c.slug}.csv\` → review → **don't Post until §2–§4 done**.

## 2. Campaign settings (manual)
- Networks: Search only — **uncheck Search partners + Display**.
- Locations: India; Location options → **Presence** (not presence-or-interest).
- Languages: English + Hindi.
- Bidding: **Maximize Clicks** now → switch to **Maximize Conversions after 15–20 conversions**.

## 3. Negative keyword list (shared "Web Dev — Global Negatives")
\`\`\`
${NEGATIVES.join("\n")}
\`\`\`

## 4. Extensions (campaign level)
- **Sitelinks:** Get a Free Quote · See Live Work · Our Process · Talk on WhatsApp → all ${c.finalUrl}
- **Callouts:** ${CALLOUTS.join(" · ")}
- **Structured snippet:** ${STRUCTURED_SNIPPET.header} → ${STRUCTURED_SNIPPET.values.join(", ")}
- **Call asset:** ${PHONE}

## 5. Pre-launch checklist
- [ ] CSV imported, Final URL = ${c.finalUrl} (loads, renders, mobile OK)
- [ ] Display + Search partners OFF · Geo India presence · Negatives attached
- [ ] Conversion tracking firing (form submit + WhatsApp click)
- [ ] Budget ₹${DAILY_BUDGET}/day · payment valid · bidding = Maximize Clicks
- [ ] RSA Ad Strength "Good"+ · Post in Editor
`;
}

const built: Campaign[] = [];
const skipped: string[] = [];

for (const g of keywordGroups) {
  if (slugFilter && g.slug !== slugFilter) continue;
  const routePath = routeMap.get(g.slug);
  if (!routePath) {
    skipped.push(g.slug);
    continue;
  }
  const c = buildCampaign(g, routePath);
  built.push(c);
  fs.writeFileSync(path.join(OUT, `${c.slug}.csv`), toEditorCsv([c]));
  fs.writeFileSync(path.join(OUT, `${c.slug}.md`), companionMd(c));
}

if (!slugFilter && built.length) {
  fs.writeFileSync(path.join(OUT, "all-campaigns.csv"), toEditorCsv(built));
}

console.log(`\nGoogle Ads sync — domain ${DOMAIN}\n${"─".repeat(52)}`);
for (const c of built) {
  console.log(`  ✓ ${c.slug.padEnd(34)} ${c.keywords.length} kw · ${c.headlines.length} H · ${c.descriptions.length} D`);
}
for (const s of skipped) {
  console.log(`  ⚠ ${s.padEnd(34)} SKIPPED — no dedicated route (would 404)`);
}
console.log(`${"─".repeat(52)}\n  ${built.length} campaign file(s) → docs/ads/  ·  ${skipped.length} skipped`);
if (built.length && !slugFilter) console.log("  + docs/ads/all-campaigns.csv (combined)\n");
else console.log("");

if (push) {
  if (!apiCredentialsPresent()) {
    console.error("⚠ --push requested but Google Ads API credentials are not set (see scripts/ads/to-ads-api.mts).");
    process.exit(1);
  }
  await pushToGoogleAds(built);
}
